// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIy3gSEZSUyZJdS35_Vj4XTGY0fCX_w70',
    appId: '1:859835648756:web:8d33ae508a85264413eca1',
    messagingSenderId: '859835648756',
    projectId: 'airbnbfake-ff305',
    authDomain: 'airbnbfake-ff305.firebaseapp.com',
    storageBucket: 'airbnbfake-ff305.firebasestorage.app',
    measurementId: 'G-P197LSSD86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjrKkqsq_7iLCQZZ6r2RY5m1UQ2K62X8',
    appId: '1:859835648756:android:e44096b153e16abf13eca1',
    messagingSenderId: '859835648756',
    projectId: 'airbnbfake-ff305',
    storageBucket: 'airbnbfake-ff305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSDMX1Zj8-xWegT578WXom7BIsHH5Wwc0',
    appId: '1:859835648756:ios:94ecb0ebb56de75013eca1',
    messagingSenderId: '859835648756',
    projectId: 'airbnbfake-ff305',
    storageBucket: 'airbnbfake-ff305.firebasestorage.app',
    iosBundleId: 'com.example.hotels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSDMX1Zj8-xWegT578WXom7BIsHH5Wwc0',
    appId: '1:859835648756:ios:94ecb0ebb56de75013eca1',
    messagingSenderId: '859835648756',
    projectId: 'airbnbfake-ff305',
    storageBucket: 'airbnbfake-ff305.firebasestorage.app',
    iosBundleId: 'com.example.hotels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIy3gSEZSUyZJdS35_Vj4XTGY0fCX_w70',
    appId: '1:859835648756:web:960ff92887dd5bd313eca1',
    messagingSenderId: '859835648756',
    projectId: 'airbnbfake-ff305',
    authDomain: 'airbnbfake-ff305.firebaseapp.com',
    storageBucket: 'airbnbfake-ff305.firebasestorage.app',
    measurementId: 'G-FBPFWTP685',
  );
}
